apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyosk-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyosk-backend
  template:
    metadata:
      labels:
        app: kyosk-backend
    spec:
      #imagePullSecrets:
      #- name: ghcr-secret
      containers:
      - name: kyosk-backend
        image: ghcr.io/oumadennisomondi/kyosk-backend:8c390f14920e6545d3ab320303e8386cdaeeb2a3
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "250Mi"
        env:
        - name: SPRING_DATA_MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: mongodb-host
        - name: SPRING_DATA_MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: mongodb-port
        - name: SPRING_DATA_MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: mongodb-database
        - name: SPRING_DATA_MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: SPRING_DATA_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyosk-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyosk-frontend
  template:
    metadata:
      labels:
        app: kyosk-frontend
    spec:
      #imagePullSecrets:
      #- name: ghcr-secret
      containers:
      - name: kyosk-frontend
        image: ghcr.io/oumadennisomondi/kyosk-frontend:8c390f14920e6545d3ab320303e8386cdaeeb2a3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://kyosk.local"
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "250Mi"
